config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :snippets
    end
  end

  resources :snippets

  root 'snippets#index'

end

app/models/snippet.rb
# encoding: UTF-8
class Snippet < ActiveRecord::Base

  validates :description, presence: true

  scope :without_private_snippet, -> { where(is_private: false) }
  scope :with_private_snippet, -> { where(is_private: true) }

  paginates_per 20

  def self.search(q)
    where('description like ?', "%#{q}%")
  end

end

app/controllers/api/v1/snippets_controller.rb
class Api::V1::SnippetsController < SnippetsController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  def index
    if params[:search].present?
      @snippets = Snippet.search(params[:search]).without_private_snippet.page params[:page]
    else
      @snippets = Snippet.without_private_snippet.page params[:page]
    end
    respond_to do |format|
      format.html
      format.json { render json: @snippets, status: 'success' }
    end
  end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new(snippet_params)
    respond_to do |format|
      if @snippet.save
        @snippet.update_attributes(share_url: snippet_url(@snippet)) if @snippet.is_private?
        format.html { redirect_to snippet_path(@snippet), notice: 'Snippet successfully created!' }
        format.json { render json: @snippet, status: 'success' }
      else
        format.html { render action: "new" }
        format.json { render json: @snippet.errors, status: 'fail' }
      end
    end
  end

  def show
    @snippet = Snippet.find(params[:id])
    respond_to do |format|
      format.html{}
      format.json { render json: @snippet, status: 'success' }
    end
  end

  protected

  def snippet_params
    params.require(:snippet).permit(:description, :is_private, :share_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Snippets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <nav class="navbar navbar-default navbar-fixed-top">
      <a href='/'><h1>Snippets</h1></a>
    </nav>
    <div class='container' style='margin-top:100px;'>
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/snippets/index.html.erb
<div class='container'>
  <div class='span9 pull-right'>
    <p >
      <%= form_tag(root_path, :method => "get", class: "navbar-form", id: "search-form") do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Snippets" %>
          <%= submit_tag 'Search', class: 'btn btn-default'%>
        </div>
      <% end %>
    </p>
  </div>



  <div class='container'>
    <div class="row">
      <%= link_to 'Create snippet', new_snippet_path, class: 'btn btn-default' %>
      <div class='span9'>
        <table class="table table-striped">
          <tr>
            <th></th>
          </tr>
          <% @snippets.each do |snippet|%>
            <tr>
              <td><a href="<%= snippet_path(snippet)%>"><%= truncate(snippet.description, length: 20)%></a></td>
            </tr>
          <% end %>

        </table>
        <%= paginate @snippets %>
      </div>
    </div>
  </div>
</div>

app/views/snippets/new.html.erb
<div class='container'>
  <div class='span9'>
    <%= form_for  @snippet do |f| %>

      <% if @snippet.errors.any? %>
        <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>
        <ul>
          <%  @snippet.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      <% end %>
      <div class='form-group'>
        <%= f.label 'Create your snippet' %><br />
        <%= f.text_area :description, rows: '20', cols: '120'%>
      </div>
      <div class='form-group'>
        <%= f.check_box :is_private %> <span> Private </span>
      </div>
      <div class='form-group'>
        <%= f.submit 'Submit', class: 'btn btn-default'%>
      </div>

    <% end %>
  </div>
</div>

app/views/snippets/show.html.erb
<div class='container'>
  <textarea class="form-control" disabled="true"> <%= @snippet.description%></textarea>
  <div class="span9">
    <% if @snippet.is_private? %>
      <label>Share this</label>
      <input class="form-control" value="<%= @snippet.share_url %>"></input>
    <% end %>
  </div>
</div>